name: on push to main
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  deploy:
    environment:
      name: ${{ github.head_ref }}
      url: https://${{ steps.frontend.outputs.domain }}
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.actor }}
      
      - name: Install Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend
      - working-directory: backend  
        run: npm install
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: ${{ github.head_ref }}
      - uses: alonch/actions-aws-function-node@main
        id: backend
        with: 
          name: ${{ github.head_ref }}
          artifacts: backend
          entrypoint-file: src/app.js
          entrypoint-function: handler
          allow-public-access: true
          memory: 1536
          # destroy infra when PR is closed
          action: ${{github.event.action == 'closed' && 'destroy' || 'apply'}}
      
      - name: Install Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend

      - working-directory: frontend  
        run: npm install
      - working-directory: frontend
        run: REACT_APP_API_URL=${{ steps.backend.outputs.url }} npm run build
      
      - uses: alonch/actions-aws-website@main
        id: frontend
        with: 
          name: ${{ github.head_ref }}
          content-path: frontend/build
          # destroy infra when PR is closed
          action: ${{github.event.action == 'closed' && 'destroy' || 'apply'}}