name: vanjs-http
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: main
      url: https://${{ steps.frontend.outputs.domain }}
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: npm/action-setup@v4
        name: Install npm
        with:
          version: 10
          run_install: false
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.actor }}
      
      - name: Install Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend
      - working-directory: backend  
        run: npm install
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: vanjs-http
      - uses: alonch/actions-aws-function-node@main
        id: backend
        with: 
          name: vanjs-http
          artifacts: backend
          entrypoint-file: src/app.js
          entrypoint-function: handler
          allow-public-access: true
      
      - name: Install Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend

      - working-directory: frontend  
        run: npm install
      - working-directory: frontend
        run: REACT_APP_API_URL=${{ steps.backend.outputs.url }} npm run build
      
      - uses: alonch/actions-aws-website@main
        id: frontend
        with: 
          content-path: frontend/build